### ISSUE TITLE
Uninstalling Global Package

### ISSUE THREAD

**Issue by delianides** [NewSpring/Norma#193]
Trying to uninstall norma-proxy fails.

```
Ø I'm getting everything ready...
Ø undefined is not a functionTypeError: undefined is not a function
  at start (/usr/local/lib/node_modules/normajs/lib/methods/run.coffee:49:15)
  at Promise._successFn (/usr/local/lib/node_modules/normajs/lib/methods/run.coffee:76:9)
  at nextTickCallback (/usr/local/lib/node_modules/normajs/node_modules/kew/kew.js:47:28)
  at process._tickDomainCallback (node.js:463:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by jbaxleyiii** [comment]
The command to uninstall is `norma remove proxy -g`

That was my bad telling you wrong @delianides
